language: java

jdk:
  - oraclejdk8
  - openjdk7
  
script: ant test

notifications:
  email:
    on_success: never
    on_failure: always
    
after_success:
  - bash <(curl -s https://codecov.io/bash)